battle/urls.py
from django.urls import path
from battle.views import home, create_room, join_room, room, battle

app_name = 'battle'
urlpatterns = [
    path('create_room/<int:game_id>/', create_room, name='create_room'),
    path('join_room/<int:room_id>/', join_room, name='join_room'),
    path('room/<int:room_id>/', room, name='room'),
    path('battle/', battle, name='battle'),
    path('', home, name='home'),
]

django_battle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('', include('battle.urls')),
]

battle/models.py
from django.db import models
from django.urls import reverse

class Lobby(models.Model):    
    title = models.CharField(max_length=50, default="Lobby")
    @property
    def group_name(self):
        """
        Returns the Channels Group name that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return self.title
    def __str__(self):
        return "Lobby"
    
class Room(models.Model):
    """
    A room for people to chat in during a game.
    """

    game = models.ForeignKey('Game', on_delete=models.CASCADE)
    blockly_workspace = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    player_one = models.CharField(max_length=50, null=True)
    player_two = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return "{} : {} vs {}".format(self.game.title, str(self.player_one), str(self.player_two))

    @property
    def group_name(self):
        """
        Returns the Channels Group name that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return "room-%s" % self.id
    
    def get_absolute_url(self):
        return reverse('battle:room', args=[self.id])

class  Game(models.Model):
    # Game title
    title = models.CharField(max_length=255)
    initial_blockly_workspace = models.TextField(default='''
        <xml>
            <block type="simulation_loop" id="initial_loop" x="36" y="32" deletable="false" movable="false"></block>
        </xml>
        ''')

    def __str__(self):
        return self.title

    @property
    def group_name(self):
        """
        Returns the Channels Game name that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return "game-%s" % self.id

migrate/models.py
from django.db import models

# Create your models here.

battle/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from battle.models import Game, Room

# Create your views here.
@login_required
def home(request):
    """
    Root page view. This is essentially a single-page app, if you ignore the
    login and admin parts.
    """
    # Get a list of rooms, ordered alphabetically
    games = Game.objects.order_by("title")
    rooms = Room.objects.filter(player_one__isnull = True)|Room.objects.filter(player_two__isnull = True)

    # Render that in the index template
    return render(request, "battle/home.html", {
        "games": games,
        "rooms": rooms,
    })

@login_required
def create_room(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    room = Room(player_one=request.user.username, game=game, blockly_workspace=game.initial_blockly_workspace)
    room.save()
    return redirect(room)

@login_required
def join_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if not room.player_one:
        room.player_one = request.user.username
    elif not room.player_two:
        room.player_two = request.user.username
    room.save()
    return redirect(room)


@login_required
def room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    return render(request, 'battle/room.html', {'room': room})

def battle(request):
    return render(request, 'battle.html')

migrate/views.py
from django.shortcuts import render

# Create your views here.

battle/templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'battle/img/favicon-32x32.png' %}">
	<link rel="stylesheet" href="{% static 'battle/css/style.css' %}" type="text/css" media="screen" />
 	<script src="{% static 'battle/js/jquery-1.12.2.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'battle/js/reconnecting-websocket.min.js' %}" type="text/javascript"></script>
	{% block extra_head %}{% endblock %}
</head>
<body>
	<div class="header">
		{% if user.is_authenticated %}
		<a id="logout" href="{% url 'logout' %}">Déconnexion</a>
		{% endif %}
		<h2>{% block header_text %}{% endblock %}</h2>
	</div>
	
	<div class="row">
		<div class="column side">{% block column_left %}{% endblock %}</div>
		<div class="column middle">{% block column_middle %}{% endblock %}</div>
		<div class="column side">{% block column_right %}{% endblock %}</div>
	</div>

	<div class="footer">{% block footer %}{% endblock %}</div>
		
		

	{% block extra_body %}{% endblock %}
</body>
</html>

battle/templates/battle.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>JsBattle Example</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.3/pixi.min.js"></script>
    <script type="text/javascript" src="{% static 'battle/js/jsbattle.min.js' %}"></script>
  </head>
  <body>
    <div style="margin: 5px 0px; padding: 5px; width: 900px; border: 1px solid #000">
      Change renderer:
      <a href="renderers.html?debug#debug">debug</a> |
      <a href="renderers.html?bw#bw">bw</a> |
      <a href="renderers.html?brody#brody">brody</a>
    </div>
    <div id="loading">LOADING...</div>
    <canvas id="battlefield" style="width: 900px; height: 600px">
    <script type="text/javascript">
      var canvas = document.getElementById('battlefield');
      var rendererList = ['debug', 'brody', 'bw'];
      var rendererName = window.location.hash.substring(1);
      rendererName = (rendererList.indexOf(rendererName) == -1) ? rendererList[0] : rendererName;

      var renderer = JsBattle.createRenderer("brody");
      renderer.init(canvas);
      renderer.loadAssets(() => {
        var simulation = JsBattle.createSimulation(renderer);
        simulation.init(900, 600);
        for(var i=0; i < 5; i++) {
          var ai = JsBattle.createAiDefinition();
          ai.fromFile('jamro');
          simulation.addTank(ai);
        }
        simulation.start();
        document.getElementById("loading").style.display ='none';
      }, '/static/battle/');
    </script>
  </body>
</html>

battle/templates/battle/home.html
{% extends "base.html" %}

{% block title %}Accueil - Lobby{% endblock %}

{% block header_text %}Accueil{% endblock %}

{% block column_left %}
    <p>Créer une partie</p>
    <ul class="games">
        {% for game in games %}
        <li class="game-link" game-url="{% url 'battle:create_room' game.id %}">{{ game }}</li>
        {% empty %}
        <p class="empty">Pas de jeu défini, créez en un via <a href="{% url 'admin:index' %}">l'administration</a> du site
        </p>
        {% endfor %}
{% endblock %}

{% block column_middle %}
    <div id="chats"></div>
{% endblock %}

{% block column_right %}
    <p>Rejoindre une partie</p>
    <ul class="rooms">
        {% for room in rooms %}
        <li class="room-link" room-url="{% url 'battle:join_room' room.id %}">
            {{ room.game }} 
            {{ room.player_one|default_if_none:"" }} 
            {{ room.player_two|default_if_none:"" }}
        </li>
        {% empty %}
        <p class="empty">Pas de partie disponible en ce moment...</p>
        {% endfor %}
    </ul>
{% endblock %}


{% block extra_body %}
<script>
    $(function () {
        // Correctly decide between ws:// and wss://
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
        console.log("Connecting to " + ws_path);
        var socket = new ReconnectingWebSocket(ws_path);
        socket.onopen = function () {
            socket.send(JSON.stringify({
                "command": "join",
                "room": "Lobby"
            }));
            console.log("Connected to lobby");
        };
        socket.onclose = function () {
            console.log("Disconnected from chat lobby");
        };
   
        // Handle incoming messages
        socket.onmessage = function (message) {
            // Decode the JSON
            console.log("Got websocket message " + message.data);
            var data = JSON.parse(message.data);
            
            // Handle errors
            if (data.error) {
                alert(data.error);
                return;
            };
                // Handle joining
                if (data.join) {
                    console.log("Joining " + data.join);
                    var chatdiv = $(
                            "<div class='game' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    chatdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": chatdiv.find("input").val()
                        }));
                        chatdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(chatdiv);
            
                } else if (data.message || data.msg_type != 0) {
                var msgdiv = $("#room-" + data.room + " .messages");
                var ok_msg = "";
                // msg types are defined in chat/settings.py
                switch (data.msg_type) {
                    case 0:
                        // Message
                        ok_msg = "<div class='message'>" +
                                "<span class='username'>" + data.username + " : </span>" +
                                "<span class='body'>" + data.message + "</span>" +
                                "</div>";
                        break;
                    case 1:
                        // Warning / Advice messages
                        ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                "</div>";
                        break;
                    case 2:
                        // Alert / Danger messages
                        ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                "</div>";
                        break;
                    case 3:
                        // "Muted" messages
                        ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                "</div>";
                        break;
                    case 4:
                        // User joined Lobby
                        ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                " a rejoint le salon" +
                                "</div>";
                        break;
                    case 5:
                        // User left Lobby
                        ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                " a quitté le salon" +
                                "</div>";
                        break;
                    case 6:
                        // Updating lobby
                        ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                " a rejoint/quitté une partie" +
                                "</div>";
                        $('.rooms').html(data.rooms_list);
                        $('.room-link').click(function () {
                            if ($(this).html().includes("{{ user.username }}")) {
                                alert('Vous êtes déjà inscrit à cette partie');
                            } else {
                                window.open($(this).attr('room-url'), '_blank');
                            };
                        });
                        break;
                    default:
                        console.log("Unsupported message type!");
                        return;
                };
                msgdiv.append(ok_msg);
                msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
            } else {
                    console.log("Cannot handle message!");
            };
        };

        // Open new tab for this game, creating a new Room
        $('.game-link').click(function() {
            window.open($(this).attr('game-url'), '_blank');
        });
        // Same for started game
        $('.room-link').click(function() {
            if ($(this).html().includes("{{ user.username }}")) {
                alert('Vous êtes déjà inscrit à cette partie');
            } else {
                window.open($(this).attr('room-url'), '_blank');
            };
        });
    });
</script>
{% endblock %}

battle/templates/battle/room.html
{% extends "base.html" %}

{% block title %}Room{% endblock %}
{% load static %}
{% block extra_head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.3/pixi.min.js"></script>
    
    <script src="{% static 'battle/js/blockly/blockly_compressed.js' %}"></script>
    <script src="{% static 'battle/js/blockly/blocks_compressed.js' %}"></script>
    <script src="{% static 'battle/js/blockly/javascript_compressed.js' %}"></script>
    <script src="{% static 'battle/js/blockly/msg/js/fr.js' %}"></script>
    
    <script src="{% static 'battle/js/blockly/custom_blocks.js' %}"></script>
    <script src="{% static 'battle/js/blockly/custom_generators.js' %}"></script>
    
    <script type="text/javascript" src="{% static 'battle/js/jsbattle.min.js' %}"></script>
{% endblock %}

{% block header_text %}
    {{ room.game.title|title }} - 
    <span id="player-1">{{ room.player_one|default_if_none:"" }}</span>
    <span id="player-2">{{ room.player_two|default_if_none:"" }}</span>
    <ul class="room">
        <li class="leave">Quitter la partie</li>
    </ul>
{% endblock %}

{% block column_left %}
<div id="blocklyDiv" style="height: 600px; width: 600px;"></div>
<div id="share-workspace" class="button">Partager l'espace de travail</div>
<div id="show-code" class="button">Show code</div>
<div id="run-code" class="button">Run code</div>

{% endblock %}

{% block column_middle %}

<!-- The Modal -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>Some text in the Modal..</p>
        <canvas id="battlefield" style="width: 900px; height: 600px"></canvas>
    </div>

</div>
<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    // var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // // When the user clicks the button, open the modal 
    // btn.onclick = function () {
    //     modal.style.display = "block";
    // }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

    <div id="chats"></div>
{% endblock %}

{% block column_right %}
<div id="opponentBlocklyDiv" style="height: 600px; width: 600px; display:none;"></div>

{% endblock %}

{% block footer %}

{% endblock %}


{% block content %}
{% endblock %}


{% block extra_body %}
<script>

    $(function () {
        var assetsLoaded = false;
        var shareWorkspace = false;
        var sharingWorkspace = false;
        var enableWorkspaceControl = false;
        var opponentWorkspace;
        var my_code;
        var his_code = `
importScripts('lib/tank.js');
tank.init(function(settings, info) {

})
tank.loop(function(state, control) {
  control.THROTTLE = 1;
});`;
        // Socket management
        // Correctly decide between ws:// and wss://
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
        console.log("Connecting to " + ws_path);
        var socket = new ReconnectingWebSocket(ws_path);
        
        socket.onopen = function () {
            socket.send(JSON.stringify({
                "command": "join",
                "room": "{{ room.id }}"
            }));
            console.log("Connected to room {{ room.id }}" );
        };
        socket.onclose = function () {
            console.log("Disconnected from room {{ room.id }}");
        };

        // Handle incoming messages
        socket.onmessage = function (message) {
            // Decode the JSON
            console.log("Got websocket message " + message.data);
            var data = JSON.parse(message.data);

            // Handle errors
            if (data.error) {
                alert(data.error);
                return;
            };
            // Handle joining
            if (data.join) {
                console.log("Joining lobby " + data.join);
                var chatdiv = $(
                    "<div class='game' id='room-" + data.join + "'>" +
                    "<h2>" + "Chat" + "</h2>" +
                    "<div class='messages'></div>" +
                    "<form><input><button>Send</button></form>" +
                    "</div>"
                );
                // Hook up send button to send a message
                chatdiv.find("form").on("submit", function () {
                    socket.send(JSON.stringify({
                        "command": "send",
                        "room": data.join,
                        "message": chatdiv.find("input").val()
                    }));
                    chatdiv.find("input").val("");
                    return false;
                });
                $("#chats").append(chatdiv);

            } else if (data.leave) {
                console.log("Leaving game " + data.leave);
                close();
                return false;
            } else if (data.message || data.msg_type != 0) {
                var msgdiv = $("#room-" + data.room + " .messages");
                var ok_msg = "";
                // msg types are defined in chat/settings.py
                switch (data.msg_type) {
                    case 0:
                        // Message
                        ok_msg = "<div class='message'>" +
                            "<span class='username'>" + data.username + " : </span>" +
                            "<span class='body'>" + data.message + "</span>" +
                            "</div>";
                        break;
                    case 1:
                        // Enable workspace sharing
                        if (!shareWorkspace) {
                            shareWorkspace = true;
                            
                            ok_msg = "<div class='contextual-message text-warning'>" + data.username +
                                " partage son espace de travail</div>";
                            $('#opponentBlocklyDiv').css('display', 'block');
                            // Creates and populate opponent's workspace with base element
                            if (!opponentWorkspace) {
                                opponentWorkspace = Blockly.inject('opponentBlocklyDiv',
                                    {
                                        toolbox: document.getElementById('myToolbox'),
                                        zoom: { startScale: 0.8 }
                                    });                            
                            }
                            Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(data.message), opponentWorkspace);
                        } else {
                            shareWorkspace = false;
                            
                            ok_msg = "<div class='contextual-message text-warning'>" + data.username +
                                " ne partage plus son espace de travail</div>";
                            opponentWorkspace.clear();
                            $('#opponentBlocklyDiv').css('display', 'none');
                        };
                        break;
                    case 2:
                        // Alert / Danger messages
                        ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                            "</div>";
                        break;
                    case 3:
                        // "Muted" messages
                        ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                            "</div>";
                        break;
                    case 4:
                        // User joined Lobby
                        ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                            " a rejoint le salon" +
                            "</div>";
                        break;
                    case 5:
                        // User left Lobby
                        ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                            " a quitté le salon" +
                            "</div>";
                        break;
                    case 8:
                        opponentWorkspace.clear();
                        Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(data.message), opponentWorkspace);
                        break;
                    default:
                        console.log("Unsupported message type!");
                        return;
                };
                msgdiv.append(ok_msg);
                msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
            } else {
                console.log("Cannot handle message!");
            };
        };
        
        // Misc hookup functions
        $('li.leave').click(function () {
            socket.send(JSON.stringify({
                "command": "leave",
                "room": "{{ room.id }}"
            }));
        });
        
        $('#share-workspace').click(function () {
            var xml = Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace));
            if (!sharingWorkspace) {
                sharingWorkspace = true;
                $('#share-workspace').text("Arrêter le partage");
            } else {
                sharingWorkspace = false;
                $('#share-workspace').text("Partager l'espace de travail");
            };
            console.log('sharing workspace' + xml);
            socket.send(JSON.stringify({
                "command": "share",
                "room": "{{ room.id }}",
                "message": xml
            }));
        });
        
        $('#show-code').click(function () {
            console.log('sending code' + Blockly.Xml.workspaceToDom(workspace));
            socket.send(JSON.stringify({
                "command": "send_code",
                "room": "{{ room.id }}",
                "message": Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace))
            }));
        });
        $('#run-code').click(function () {
            console.log(my_code);
            console.log(his_code);
            var canvas = document.getElementById('battlefield');
            var renderer = JsBattle.createRenderer("brody");
            var simulation;
            renderer.init(canvas);
            if (!assetsLoaded) {
                renderer.loadAssets(() => {
                    assetsLoaded = true;
                    simulation = JsBattle.createSimulation(renderer);
                    simulation.init(900, 600);
                    var ai = JsBattle.createAiDefinition();
                    ai.fromCode('me', my_code);
                    simulation.addTank(ai);
                    ai = JsBattle.createAiDefinition();
                    ai.fromCode('him', his_code);
                    simulation.addTank(ai);
                    simulation.start();
                }, '/static/battle/');
            } else {
                simulation = JsBattle.createSimulation(renderer);
                simulation.init(900, 600);
                var ai = JsBattle.createAiDefinition();
                ai.fromCode('me', my_code);
                simulation.addTank(ai);
                ai = JsBattle.createAiDefinition();
                ai.fromCode('him', his_code);
                simulation.addTank(ai);
                simulation.start();
            };
            $('#myModal').css('display', 'block');

        });

        // Blockly workspace management
        // Initialize and populates my workspace
        var workspace = Blockly.inject('blocklyDiv',
            { 
                toolbox: document.getElementById('myToolbox'),
                zoom: {startScale : 0.8}
            });
        Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom('<xml><block type="simulation_loop" id="initial_loop" x="36" y="32" deletable="false" movable="false"></block></xml>'), workspace);
        function myUpdateFunction(event) {
            if (event.type != Blockly.Events.UI && event.type != Blockly.Events.CREATE) {
                my_code = Blockly.JavaScript.workspaceToCode(workspace);
                if (shareWorkspace) {
                    socket.send(JSON.stringify({
                        "command": "send_workspace",
                        "room": "{{ room.id }}",
                        "message": Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace))
                    }));
                };
            };
            console.log('Updating my code : ' + my_code);
        };
        workspace.addChangeListener(myUpdateFunction);
        
    });
</script>
<xml id="myToolbox" style="display: none">
    <!--
  <block type="controls_if"></block>
  <block type="controls_repeat_ext"></block>
  <block type="logic_compare"></block>
  <block type="math_number"></block>
  <block type="math_arithmetic"></block>
-->
    <block type="logic_compare"></block>
    <block type="controls_if"></block>
    <block type="math_number"></block>
    <block type="text"></block>
    <block type="text_print"></block>
    <!--
  <block type="simulation_loop"></block>
-->
    <block type="update_control"></block>
    <block type="shoot"></block>
    <block type="input_position"></block>
    <block type="state_radar"></block>

</xml>
{% endblock %}

battle/templates/battle/rooms_list.html
{% for room in rooms %}
<li class="room-link" room-url="{% url 'battle:join_room' room.id %}">
    {{ room.game }}
    {{ room.player_one|default_if_none:"" }}
    {{ room.player_two|default_if_none:"" }}
</li>
{% empty %}
<p class="empty">Pas de partie disponible en ce moment...</p>
{% endfor %}